name: release-ci

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate mvn settings xml
        uses: s4u/maven-settings-action@v2.1.1
        with:
          servers: '[{"id": "maven.jenkins-ci.org", "username": "${{ secrets.JENKINS_CI_USERNAME }}", "password": "${{ secrets.JENKINS_CI_PASSWORD }}"}]'

      - name: set release version
        run: |
          ./mvnw install
          ./mvnw release:update-versions -DautoVersionSubmodules=true
#        run: ./mvnw install -Pit
#      - name: Prepare for release
#        run: echo -ne '\n' | ./mvnw gitflow:release-start gitflow:release-finish

      - name: deploy hpi to jenkins-ci
        run: ./mvnw deploy:deploy
