name: release-ci

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env variables
        run: echo "set some necessary env-vars"
        env:
          JENKINS_CI_USERNAME: ${{ secrets.JENKINS_CI_USERNAME }}
          JENKINS_CI_PASSWORD: ${{ secrets.JENKINS_CI_PASSWORD }}
      - name: Set up Git Creds
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and invoke integration test HPI
        run: ./mvnw install
#        run: ./mvnw install -Pit
      - name: Prepare for release
        run: ./mvnw gitflow:release-start -B
      - name: Deploy to CI
        run: ./mvnw gitflow:release-finish
#      - name: Commit changes to master
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: 'master'
#          tags: true
#      - name: Commit changes to dev
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: 'dev'
#          tags: true
